#############################################################################################
# These workflows are for demonstrations purposes only and should not be used in production #
#############################################################################################
# To learn more about GitHub Actions, please see the official documentation:                #
# - https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions    #
#                                                                                           #
# To learn more about the actions used, please refer to the GitHub marketplace:             #
# - https://github.com/marketplace                                                          #
#############################################################################################

name: Deploy - Continous Delivery

# The on code block below demonstrates that if branch protections are enabled, that 
# the only time a continuous delivery (CD) workflow will execute is when a pull request
# is merged into the main branch
on: 
  push:
    branches:
      - 'master'

# The 'env' block is used for declaring environment variables that will be used in our 
# workflow. These variables can be recalled by using the expressions syntax '${{ <expression. }}'
# For more information on expressions and retrieving environment variables and secrets, see
# https://docs.github.com/en/actions/learn-github-actions/expressions
env:
  AZURE_CONTAINER_REGISTRY: MY_REGISTRY_NAME # set this to the name of your container registry
  PROJECT_NAME: MY_PROJECT_NAME              # set this to your project's name
  RESOURCE_GROUP: MY_RESOURCE_GROUP          # set this to the resource group containing your AKS cluster
  CLUSTER_NAME: MY_CLUSTER_NAME              # set this to the name of your AKS cluster
  REGISTRY_URL: MY_REGISTRY_URL              # set this to the URL of your registry
  MANIFEST_PATH: MY_HELM_FILE                   # set this to the path to your helm file

jobs:
  build:
    # Defines the runner we want to use for executing this workflow.
    # More about choosing a runner: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build image on ACR
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          # Sets default azure container registry using environment variable above
          az configure --defaults acr=${{ env.AZURE_CONTAINER_REGISTRY }}
          
          az acr build -t ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
    
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v2.0

    - name: Gets K8s context
      uses: azure/aks-set-context@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

    - name: Deploy our Orleans application!
      uses: Azure/k8s-deploy@v1.4
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.PROJECT_NAME }}:${{ github.sha }}
        imagepullsecrets: |
          ${{ env.PROJECT_NAME }}
